### ISSUE TITLE
Unable to run rake teaspoon: "closed stream (IOError)"

### ISSUE THREAD

**Issue by thesauri** [jejacks0n/teaspoon#509]
Hello, I'm trying to run teaspoon with JRuby 9.0.5.0 and Rails 4.2.7. I followed the README instructions and [the quick start walkthrough](https://github.com/jejacks0n/teaspoon/wiki/Quick-Start-Walkthrough). However, when I try to run the tests I get the following error:

```
dhcp-86-168:cruncher user$ rake teaspoon
Starting the Teaspoon server...
Puma starting in single mode...
* Version 3.6.0 (jruby 9.0.5.0 - ruby 2.2.3), codename: Sleepy Sunday Serenity
* Min threads: 0, max threads: 16
* Environment: test
* Listening on tcp://127.0.0.1:55197
Teaspoon running default suite at http://127.0.0.1:55197/teaspoon/default
Use Ctrl-C to stop


Finished in 0.01100 seconds
0 examples, 0 failures

Error in reactor loop escaped: closed stream (IOError)
org/jruby/RubyIO.java:3001:in `read'
org/jruby/RubyIO.java:2958:in `read'
/Users/user/.rvm/gems/jruby-9.0.5.0/gems/puma-3.6.0-java/lib/puma/reactor.rb:45:in `block in run_internal'
org/jruby/ext/thread/Mutex.java:151:in `synchronize'
/Users/user/.rvm/gems/jruby-9.0.5.0/gems/puma-3.6.0-java/lib/puma/reactor.rb:44:in `block in run_internal'
org/jruby/RubyArray.java:1560:in `each'
/Users/user/.rvm/gems/jruby-9.0.5.0/gems/puma-3.6.0-java/lib/puma/reactor.rb:42:in `run_internal'
/Users/user/.rvm/gems/jruby-9.0.5.0/gems/puma-3.6.0-java/lib/puma/reactor.rb:153:in `block in run_in_thread'
Error in select: closed stream (IOError)
org/jruby/RubyIO.java:3348:in `select'
/Users/user/.rvm/gems/jruby-9.0.5.0/gems/puma-3.6.0-java/lib/puma/reactor.rb:29:in `run_internal'
/Users/user/.rvm/gems/jruby-9.0.5.0/gems/puma-3.6.0-java/lib/puma/reactor.rb:153:in `block in run_in_thread'
```

If I run the command using `rake teaspoon RAILS_ENV=test` the test server starts, but crashes as soon I try to access the page:

```
dhcp-86-168:cruncher user$ rake teaspoon RAILS_ENV=test
Starting the Teaspoon server...
Puma starting in single mode...
* Version 3.6.0 (jruby 9.0.5.0 - ruby 2.2.3), codename: Sleepy Sunday Serenity
* Min threads: 0, max threads: 16
* Environment: test
* Listening on tcp://127.0.0.1:60897
Use Ctrl-C to stop
Teaspoon running default suite at http://127.0.0.1:60897/teaspoon/default


Finished in 0.00500 seconds
0 examples, 0 failures

Error in select: closed stream (IOError)
org/jruby/RubyIO.java:3348:in `select'
/Users/user/.rvm/gems/jruby-9.0.5.0/gems/puma-3.6.0-java/lib/puma/reactor.rb:29:in `run_internal'
/Users/user/.rvm/gems/jruby-9.0.5.0/gems/puma-3.6.0-java/lib/puma/reactor.rb:153:in `block in run_in_thread'
2017-01-10 20:29:36 +0200: Listen loop error: #<IOError: closed stream>
org/jruby/RubyIO.java:3348:in `select'
/Users/user/.rvm/gems/jruby-9.0.5.0/gems/puma-3.6.0-java/lib/puma/server.rb:327:in `handle_servers'
/Users/user/.rvm/gems/jruby-9.0.5.0/gems/puma-3.6.0-java/lib/puma/server.rb:301:in `block in run'
2017-01-10 20:29:36 +0200: Listen loop error: #<IOError: closed stream>
org/jruby/RubyIO.java:3348:in `select'
/Users/user/.rvm/gems/jruby-9.0.5.0/gems/puma-3.6.0-java/lib/puma/server.rb:327:in `handle_servers'
/Users/user/.rvm/gems/jruby-9.0.5.0/gems/puma-3.6.0-java/lib/puma/server.rb:301:in `block in run'
2017-01-10 20:29:36 +0200: Listen loop error: #<IOError: closed stream>
org/jruby/RubyIO.java:3348:in `select'
/Users/user/.rvm/gems/jruby-9.0.5.0/gems/puma-3.6.0-java/lib/puma/server.rb:327:in `handle_servers'
/Users/user/.rvm/gems/jruby-9.0.5.0/gems/puma-3.6.0-java/lib/puma/server.rb:301:in `block in run'
2017-01-10 20:29:36 +0200: Listen loop error: #<IOError: closed stream>
org/jruby/RubyIO.java:3348:in `select'
/Users/user/.rvm/gems/jruby-9.0.5.0/gems/puma-3.6.0-java/lib/puma/server.rb:327:in `handle_servers'
/Users/user/.rvm/gems/jruby-9.0.5.0/gems/puma-3.6.0-java/lib/puma/server.rb:301:in `block in run'
2017-01-10 20:29:36 +0200: Listen loop error: #<IOError: closed stream>
org/jruby/RubyIO.java:3348:in `select'
/Users/user/.rvm/gems/jruby-9.0.5.0/gems/puma-3.6.0-java/lib/puma/server.rb:327:in `handle_servers'
/Users/user/.rvm/gems/jruby-9.0.5.0/gems/puma-3.6.0-java/lib/puma/server.rb:301:in `block in run'
2017-01-10 20:29:36 +0200: Listen loop error: #<IOError: closed stream>
org/jruby/RubyIO.java:3348:in `select'
/Users/user/.rvm/gems/jruby-9.0.5.0/gems/puma-3.6.0-java/lib/puma/server.rb:327:in `handle_servers'
/Users/user/.rvm/gems/jruby-9.0.5.0/gems/puma-3.6.0-java/lib/puma/server.rb:301:in `block in run'
2017-01-10 20:29:36 +0200: Listen loop error: #<IOError: closed stream>
org/jruby/RubyIO.java:3348:in `select'
/Users/user/.rvm/gems/jruby-9.0.5.0/gems/puma-3.6.0-java/lib/puma/server.rb:327:in `handle_servers'
/Users/user/.rvm/gems/jruby-9.0.5.0/gems/puma-3.6.0-java/lib/puma/server.rb:301:in `block in run'
2017-01-10 20:29:36 +0200: Listen loop error: #<IOError: closed stream>
org/jruby/RubyIO.java:3348:in `select'
/Users/user/.rvm/gems/jruby-9.0.5.0/gems/puma-3.6.0-java/lib/puma/server.rb:327:in `handle_servers'
/Users/user/.rvm/gems/jruby-9.0.5.0/gems/puma-3.6.0-java/lib/puma/server.rb:301:in `block in run'
2017-01-10 20:29:36 +0200: Listen loop error: #<IOError: closed stream>
org/jruby/RubyIO.java:3348:in `select'
/Users/user/.rvm/gems/jruby-9.0.5.0/gems/puma-3.6.0-java/lib/puma/server.rb:327:in `handle_servers'
/Users/user/.rvm/gems/jruby-9.0.5.0/gems/puma-3.6.0-java/lib/puma/server.rb:301:in `block in run'
2017-01-10 20:29:36 +0200: Listen loop error: #<IOError: closed stream>
org/jruby/RubyIO.java:3348:in `select'
/Users/user/.rvm/gems/jruby-9.0.5.0/gems/puma-3.6.0-java/lib/puma/server.rb:327:in `handle_servers'
/Users/user/.rvm/gems/jruby-9.0.5.0/gems/puma-3.6.0-java/lib/puma/server.rb:301:in `block in run'
2017-01-10 20:29:36 +0200: Listen loop error: #<IOError: closed stream>
org/jruby/RubyIO.java:3348:in `select'
/Users/user/.rvm/gems/jruby-9.0.5.0/gems/puma-3.6.0-java/lib/puma/server.rb:327:in `handle_servers'
/Users/user/.rvm/gems/jruby-9.0.5.0/gems/puma-3.6.0-java/lib/puma/server.rb:301:in `block in run'
2017-01-10 20:29:36 +0200: Listen loop error: #<IOError: closed stream>
org/jruby/RubyIO.java:3348:in `select'
/Users/user/.rvm/gems/jruby-9.0.5.0/gems/puma-3.6.0-java/lib/puma/server.rb:327:in `handle_servers'
/Users/user/.rvm/gems/jruby-9.0.5.0/gems/puma-3.6.0-java/lib/puma/server.rb:301:in `block in run'
2017-01-10 20:29:36 +0200: Listen loop error: #<IOError: closed stream>
org/jruby/RubyIO.java:3348:in `select'
/Users/user/.rvm/gems/jruby-9.0.5.0/gems/puma-3.6.0-java/lib/puma/server.rb:327:in `handle_servers'
/Users/user/.rvm/gems/jruby-9.0.5.0/gems/puma-3.6.0-java/lib/puma/server.rb:301:in `block in run'
2017-01-10 20:29:36 +0200: Listen loop error: #<IOError: closed stream>
org/jruby/RubyIO.java:3348:in `select'
/Users/user/.rvm/gems/jruby-9.0.5.0/gems/puma-3.6.0-java/lib/puma/server.rb:327:in `handle_servers'
/Users/user/.rvm/gems/jruby-9.0.5.0/gems/puma-3.6.0-java/lib/puma/server.rb:301:in `block in run'
2017-01-10 20:29:36 +0200: Listen loop error: #<IOError: closed stream>
org/jruby/RubyIO.java:3348:in `select'
/Users/user/.rvm/gems/jruby-9.0.5.0/gems/puma-3.6.0-java/lib/puma/server.rb:327:in `handle_servers'
/Users/user/.rvm/gems/jruby-9.0.5.0/gems/puma-3.6.0-java/lib/puma/server.rb:301:in `block in run'
2017-01-10 20:29:36 +0200: Listen loop error: #<IOError: closed stream>
org/jruby/RubyIO.java:3348:in `select'
/Users/user/.rvm/gems/jruby-9.0.5.0/gems/puma-3.6.0-java/lib/puma/server.rb:327:in `handle_servers'
/Users/user/.rvm/gems/jruby-9.0.5.0/gems/puma-3.6.0-java/lib/puma/server.rb:301:in `block in run'
2017-01-10 20:29:36 +0200: Listen loop error: #<IOError: closed stream>
org/jruby/RubyIO.java:3348:in `select'
/Users/user/.rvm/gems/jruby-9.0.5.0/gems/puma-3.6.0-java/lib/puma/server.rb:327:in `handle_servers'
/Users/user/.rvm/gems/jruby-9.0.5.0/gems/puma-3.6.0-java/lib/puma/server.rb:301:in `block in run'
2017-01-10 20:29:36 +0200: Listen loop error: #<IOError: closed stream>
org/jruby/RubyIO.java:3348:in `select'
/Users/user/.rvm/gems/jruby-9.0.5.0/gems/puma-3.6.0-java/lib/puma/server.rb:327:in `handle_servers'
/Users/user/.rvm/gems/jruby-9.0.5.0/gems/puma-3.6.0-java/lib/puma/server.rb:301:in `block in run'
2017-01-10 20:29:36 +0200: Listen loop error: #<IOError: closed stream>
org/jruby/RubyIO.java:3348:in `select'
/Users/user/.rvm/gems/jruby-9.0.5.0/gems/puma-3.6.0-java/lib/puma/server.rb:327:in `handle_servers'
/Users/user/.rvm/gems/jruby-9.0.5.0/gems/puma-3.6.0-java/lib/puma/server.rb:301:in `block in run'
2017-01-10 20:29:36 +0200: Listen loop error: #<IOError: closed stream>
org/jruby/RubyIO.java:3348:in `select'
/Users/user/.rvm/gems/jruby-9.0.5.0/gems/puma-3.6.0-java/lib/puma/server.rb:327:in `handle_servers'
/Users/user/.rvm/gems/jruby-9.0.5.0/gems/puma-3.6.0-java/lib/puma/server.rb:301:in `block in run'
2017-01-10 20:29:36 +0200: Listen loop error: #<IOError: closed stream>
org/jruby/RubyIO.java:3348:in `select'
/Users/user/.rvm/gems/jruby-9.0.5.0/gems/puma-3.6.0-java/lib/puma/server.rb:327:in `handle_servers'
/Users/user/.rvm/gems/jruby-9.0.5.0/gems/puma-3.6.0-java/lib/puma/server.rb:301:in `block in run'
2017-01-10 20:29:36 +0200: Listen loop error: #<IOError: closed stream>
org/jruby/RubyIO.java:3348:in `select'
/Users/user/.rvm/gems/jruby-9.0.5.0/gems/puma-3.6.0-java/lib/puma/server.rb:327:in `handle_servers'
/Users/user/.rvm/gems/jruby-9.0.5.0/gems/puma-3.6.0-java/lib/puma/server.rb:301:in `block in run'
2017-01-10 20:29:36 +0200: Listen loop error: #<IOError: closed stream>
org/jruby/RubyIO.java:3348:in `select'
/Users/user/.rvm/gems/jruby-9.0.5.0/gems/puma-3.6.0-java/lib/puma/server.rb:327:in `handle_servers'
/Users/user/.rvm/gems/jruby-9.0.5.0/gems/puma-3.6.0-java/lib/puma/server.rb:301:in `block in run'
2017-01-10 20:29:36 +0200: Listen loop error: #<IOError: closed stream>
org/jruby/RubyIO.java:3348:in `select'
/Users/user/.rvm/gems/jruby-9.0.5.0/gems/puma-3.6.0-java/lib/puma/server.rb:327:in `handle_servers'
/Users/user/.rvm/gems/jruby-9.0.5.0/gems/puma-3.6.0-java/lib/puma/server.rb:301:in `block in run'
2017-01-10 20:29:36 +0200: Listen loop error: #<IOError: closed stream>
org/jruby/RubyIO.java:3348:in `select'
/Users/user/.rvm/gems/jruby-9.0.5.0/gems/puma-3.6.0-java/lib/puma/server.rb:327:in `handle_servers'
/Users/user/.rvm/gems/jruby-9.0.5.0/gems/puma-3.6.0-java/lib/puma/server.rb:301:in `block in run'
2017-01-10 20:29:36 +0200: Listen loop error: #<IOError: closed stream>
org/jruby/RubyIO.java:3348:in `select'
/Users/user/.rvm/gems/jruby-9.0.5.0/gems/puma-3.6.0-java/lib/puma/server.rb:327:in `handle_servers'
/Users/user/.rvm/gems/jruby-9.0.5.0/gems/puma-3.6.0-java/lib/puma/server.rb:301:in `block in run'
2017-01-10 20:29:36 +0200: Listen loop error: #<IOError: closed stream>
org/jruby/RubyIO.java:3348:in `select'
/Users/user/.rvm/gems/jruby-9.0.5.0/gems/puma-3.6.0-java/lib/puma/server.rb:327:in `handle_servers'
/Users/user/.rvm/gems/jruby-9.0.5.0/gems/puma-3.6.0-java/lib/puma/server.rb:301:in `block in run'
2017-01-10 20:29:36 +0200: Listen loop error: #<IOError: closed stream>
org/jruby/RubyIO.java:3348:in `select'
/Users/user/.rvm/gems/jruby-9.0.5.0/gems/puma-3.6.0-java/lib/puma/server.rb:327:in `handle_servers'
/Users/user/.rvm/gems/jruby-9.0.5.0/gems/puma-3.6.0-java/lib/puma/server.rb:301:in `block in run'
2017-01-10 20:29:36 +0200: Listen loop error: #<IOError: closed stream>
org/jruby/RubyIO.java:3348:in `select'
/Users/user/.rvm/gems/jruby-9.0.5.0/gems/puma-3.6.0-java/lib/puma/server.rb:327:in `handle_servers'
/Users/user/.rvm/gems/jruby-9.0.5.0/gems/puma-3.6.0-java/lib/puma/server.rb:301:in `block in run'
2017-01-10 20:29:36 +0200: Listen loop error: #<IOError: closed stream>
org/jruby/RubyIO.java:3348:in `select'
/Users/user/.rvm/gems/jruby-9.0.5.0/gems/puma-3.6.0-java/lib/puma/server.rb:327:in `handle_servers'
/Users/user/.rvm/gems/jruby-9.0.5.0/gems/puma-3.6.0-java/lib/puma/server.rb:301:in `block in run'
2017-01-10 20:29:36 +0200: Listen loop error: #<IOError: closed stream>
org/jruby/RubyIO.java:3348:in `select'
/Users/user/.rvm/gems/jruby-9.0.5.0/gems/puma-3.6.0-java/lib/puma/server.rb:327:in `handle_servers'
/Users/user/.rvm/gems/jruby-9.0.5.0/gems/puma-3.6.0-java/lib/puma/server.rb:301:in `block in run'
2017-01-10 20:29:36 +0200: Listen loop error: #<IOError: closed stream>
org/jruby/RubyIO.java:3348:in `select'
/Users/user/.rvm/gems/jruby-9.0.5.0/gems/puma-3.6.0-java/lib/puma/server.rb:327:in `handle_servers'
/Users/user/.rvm/gems/jruby-9.0.5.0/gems/puma-3.6.0-java/lib/puma/server.rb:301:in `block in run'
2017-01-10 20:29:36 +0200: Listen loop error: #<IOError: closed stream>
org/jruby/RubyIO.java:3348:in `select'
/Users/user/.rvm/gems/jruby-9.0.5.0/gems/puma-3.6.0-java/lib/puma/server.rb:327:in `handle_servers'
/Users/user/.rvm/gems/jruby-9.0.5.0/gems/puma-3.6.0-java/lib/puma/server.rb:301:in `block in run'
2017-01-10 20:29:36 +0200: Listen loop error: #<IOError: closed stream>
org/jruby/RubyIO.java:3348:in `select'
/Users/user/.rvm/gems/jruby-9.0.5.0/gems/puma-3.6.0-java/lib/puma/server.rb:327:in `handle_servers'
/Users/user/.rvm/gems/jruby-9.0.5.0/gems/puma-3.6.0-java/lib/puma/server.rb:301:in `block in run'
2017-01-10 20:29:36 +0200: Listen loop error: #<IOError: closed stream>
org/jruby/RubyIO.java:3348:in `select'
/Users/user/.rvm/gems/jruby-9.0.5.0/gems/puma-3.6.0-java/lib/puma/server.rb:327:in `handle_servers'
/Users/user/.rvm/gems/jruby-9.0.5.0/gems/puma-3.6.0-java/lib/puma/server.rb:301:in `block in run'
2017-01-10 20:29:36 +0200: Listen loop error: #<IOError: closed stream>
org/jruby/RubyIO.java:3348:in `select'
/Users/user/.rvm/gems/jruby-9.0.5.0/gems/puma-3.6.0-java/lib/puma/server.rb:327:in `handle_servers'
/Users/user/.rvm/gems/jruby-9.0.5.0/gems/puma-3.6.0-java/lib/puma/server.rb:301:in `block in run'
2017-01-10 20:29:36 +0200: Listen loop error: #<IOError: closed stream>
org/jruby/RubyIO.java:3348:in `select'
/Users/user/.rvm/gems/jruby-9.0.5.0/gems/puma-3.6.0-java/lib/puma/server.rb:327:in `handle_servers'
/Users/user/.rvm/gems/jruby-9.0.5.0/gems/puma-3.6.0-java/lib/puma/server.rb:301:in `block in run'
2017-01-10 20:29:36 +0200: Listen loop error: #<IOError: closed stream>
org/jruby/RubyIO.java:3348:in `select'
/Users/user/.rvm/gems/jruby-9.0.5.0/gems/puma-3.6.0-java/lib/puma/server.rb:327:in `handle_servers'
/Users/user/.rvm/gems/jruby-9.0.5.0/gems/puma-3.6.0-java/lib/puma/server.rb:301:in `block in run'
2017-01-10 20:29:36 +0200: Listen loop error: #<IOError: closed stream>
org/jruby/RubyIO.java:3348:in `select'
/Users/user/.rvm/gems/jruby-9.0.5.0/gems/puma-3.6.0-java/lib/puma/server.rb:327:in `handle_servers'
/Users/user/.rvm/gems/jruby-9.0.5.0/gems/puma-3.6.0-java/lib/puma/server.rb:301:in `block in run'
```

Any ideas?

**Comment by joannakim** [comment]
This was posted a while ago but did you figure out what was happening, and if so do you happen to remember how you resolved this? Thanks!

**Comment by thesauri** [comment]
@joannakim Unfortunately not. If I remember correctly we gave up on using teaspoon altogether..
