### ISSUE TITLE
ReferenceError: Can't find variable: Teaspoon, jQuery

### ISSUE THREAD

**Issue by devn** [jejacks0n/teaspoon#95]
Any ideas?

```
☣ (solo)> rake teaspoon
Starting the Teaspoon server...
Teaspoon running default suite at http://127.0.0.1:49295/teaspoon/default
ReferenceError: Can't find variable: Teaspoon
  # http://127.0.0.1:49295/teaspoon/default?reporter=Console:12

ReferenceError: Can't find variable: Teaspoon
  # http://127.0.0.1:49295/teaspoon/default?reporter=Console:50

ReferenceError: Can't find variable: jQuery
  # http://127.0.0.1:49295/asset-foo/mini-profiler-resources/includes.js?v=e777c6e0fdfb9a725e857c8ca3eab18f:897

Error: Failed to load: http://127.0.0.1:49295/teaspoon/default?reporter=Console
rake aborted!

/Users/someguy/.rvm/gems/ruby-1.9.3-p194@snorkel/gems/teaspoon-0.7.4/lib/tasks/teaspoon.rake:4:in `block in <top (required)>'
/Users/someguy/.rvm/gems/ruby-1.9.3-p194@snorkel/gems/rake-10.0.4/lib/rake/task.rb:246:in `call'
/Users/someguy/.rvm/gems/ruby-1.9.3-p194@snorkel/gems/rake-10.0.4/lib/rake/task.rb:246:in `block in execute'
/Users/someguy/.rvm/gems/ruby-1.9.3-p194@snorkel/gems/rake-10.0.4/lib/rake/task.rb:241:in `each'
/Users/someguy/.rvm/gems/ruby-1.9.3-p194@snorkel/gems/rake-10.0.4/lib/rake/task.rb:241:in `execute'
/Users/someguy/.rvm/gems/ruby-1.9.3-p194@snorkel/gems/rake-10.0.4/lib/rake/task.rb:184:in `block in invoke_with_call_chain'
/Users/someguy/.rvm/gems/ruby-1.9.3-p194@snorkel/gems/rake-10.0.4/lib/rake/task.rb:177:in `invoke_with_call_chain'
/Users/someguy/.rvm/gems/ruby-1.9.3-p194@snorkel/gems/rake-10.0.4/lib/rake/task.rb:170:in `invoke'
/Users/someguy/.rvm/gems/ruby-1.9.3-p194@snorkel/gems/rake-10.0.4/lib/rake/application.rb:143:in `invoke_task'
/Users/someguy/.rvm/gems/ruby-1.9.3-p194@snorkel/gems/rake-10.0.4/lib/rake/application.rb:101:in `block (2 levels) in top_level'
/Users/someguy/.rvm/gems/ruby-1.9.3-p194@snorkel/gems/rake-10.0.4/lib/rake/application.rb:101:in `each'
/Users/someguy/.rvm/gems/ruby-1.9.3-p194@snorkel/gems/rake-10.0.4/lib/rake/application.rb:101:in `block in top_level'
/Users/someguy/.rvm/gems/ruby-1.9.3-p194@snorkel/gems/rake-10.0.4/lib/rake/application.rb:110:in `run_with_threads'
/Users/someguy/.rvm/gems/ruby-1.9.3-p194@snorkel/gems/rake-10.0.4/lib/rake/application.rb:95:in `top_level'
/Users/someguy/.rvm/gems/ruby-1.9.3-p194@snorkel/gems/rake-10.0.4/lib/rake/application.rb:73:in `block in run'
/Users/someguy/.rvm/gems/ruby-1.9.3-p194@snorkel/gems/rake-10.0.4/lib/rake/application.rb:160:in `standard_exception_handling'
/Users/someguy/.rvm/gems/ruby-1.9.3-p194@snorkel/gems/rake-10.0.4/lib/rake/application.rb:70:in `run'
/Users/someguy/.rvm/gems/ruby-1.9.3-p194@snorkel/bin/ruby_noexec_wrapper:14:in `eval'
/Users/someguy/.rvm/gems/ruby-1.9.3-p194@snorkel/bin/ruby_noexec_wrapper:14:in `<main>'
Tasks: TOP => teaspoon
(See full trace by running task with --trace)
```

**Comment by chaomao** [comment]
I have the same error, and try add the RAILS_ENV=test before teaspoon, then it works
I don't know whether it is related with spring or other preloader

**Comment by mebibou** [comment]
@chaomao you are right it solved this for me too. The strange thing is that it was working yesterday, and suddenly not anymore. What is the cause?
